# Infrared status for foscam cam in hall
- platform: command_line
  # Command used to get infrared status for a foscam camera:
  # 'curl -k --silent "https://<cam_host>:<cam_port>/cgi-bin/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=<username>&pwd=<password>" | grep -oP "(?<=infraLedState>).*?(?=</infraLedState>)"'
  command: !secret cam_hall_infrared_command
  name: cam_hall_infrared
  payload_on: '1'
  payload_off: '0'

# Infrared status for foscam cam in swimming pool
- platform: command_line
  # Command used to get infrared status for a foscam camera:
  # 'curl -k --silent "https://<cam_host>:<cam_port>/cgi-bin/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=<username>&pwd=<password>" | grep -oP "(?<=infraLedState>).*?(?=</infraLedState>)"'
  command: !secret cam_swimmingpool_infrared_command
  name: cam_swimmingpool_infrared
  payload_on: '1'
  payload_off: '0'

# UPS status
- platform: mqtt
  state_topic: 'home/ups/status'
  name: ups_status_bs
  sensor_class: light
  qos: 0
#  payload_on: 'OFF'
#  payload_off: 'ON'
  value_template: >-
          {%- if value == "ONLINE" or value == "COMMOK" %}
              ON
          {% else %}
              OFF
          {%- endif %}