- platform: bitcoin
  currency: EUR
  display_options:
    - exchangerate

- platform: efergy
  app_token: !secret efergy_app_token
  utc_offset: 2
  monitored_variables:
    - type: instant_readings

- platform: netatmo
  station: HokusWeather
  modules:
    Salón:
      - temperature
      - min_temp
      - max_temp
      - humidity
      - noise
      - pressure
      - co2
      - wifi_status
    Exterior:
      - temperature
      - min_temp
      - max_temp
      - humidity
      - battery_vp
    Pluviómetro:
      - rain
      - sum_rain_1
      - sum_rain_24
      - battery_vp

- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

- platform: mqtt
  state_topic: 'owntracks/hokusphone/hokusphone'
  name: hokusphone_batt
  unit_of_measurement: '%'
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: 'home/ups/status'
  name: ups_status
  value_template: >-
          {%- if value == "ONLINE" %}
              Con corriente
          {% elif value == "ONBATT" %}
              Usando batería
          {% elif value == "LOWBATT" %}
              Batería baja
          {% elif value == "FSD" %}
              Forced shutdown in progress
          {% elif value == "COMMOK" %}
              Comunicación establecida
          {% elif value == "COMMBAD" %}
              Comunicación perdida
          {% elif value == "SHUTDOWN" %}
              Auto logout and shutdown proceeding
          {% elif value == "RPLBATT" %}
              Reemplazar batería
          {% elif value == "NOCOMM" %}
              No disponible
          {% elif value == "NOPARENT" %}
              upsmon parent process died - shutdown impossible
          {% else %}
              Desconocido
          {%- endif %}

# Know if the Wemo Maker sensor has been triggered (on: garage door opened, off: garage door closed)
- platform: template
  sensors:
    fence_status:
        friendly_name: 'Estado'
        value_template: >-
            {%- if is_state_attr("switch.barrera", "sensor_state", "on") %}
                abierta
            {% else %}
                cerrada
            {%- endif %}

# Sensor to define roughly the season of the year (if more precission needed use another algorythm)
- platform: template
  sensors:
    season:
      friendly_name: 'Estación'
      value_template:  >-
          {%- if now().month >= 3 and now().month <= 5 %}
              Spring
          {% elif now().month >= 6 and now().month <= 8 %}
              Summer
          {% elif now().month >= 9 and now().month <= 11 %}
              Autumn
          {% else %}
              Winter
          {%- endif %}

- platform: template
  sensors:
    sunrise:
      friendly_name: 'Amanecer'
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising)|timestamp_custom("%H:%M:%S") }}'
    sunset:
      friendly_name: 'Puesta de sol'
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting)|timestamp_custom("%H:%M:%S") }}'

- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot
    - type: since_last_boot

- platform: fitbit
  monitored_resources:
    - "activities/steps"
    - "activities/distance"
    - "body/weight"
    - "sleep/efficiency"

- platform: template
  sensors:
      virtual_device:
        friendly_name: 'Persona autorizada'
        value_template: >-
            {%- if is_state("device_tracker.virtual_device", "home") %}
                En casa
            {% elif is_state("device_tracker.virtual_device", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.virtual_device.state }}
            {%- endif %}
      hokusphone_hokusphone:
        friendly_name: 'Jordi'
        value_template: >-
            {%- if is_state("device_tracker.hokusphone_hokusphone", "home") %}
                En casa
            {% elif is_state("device_tracker.hokusphone_hokusphone", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.hokusphone_hokusphone.state }}
            {%- endif %}
      geni:
        friendly_name: 'Geni'
        value_template: >-
            {%- if is_state("device_tracker.geni", "home") %}
                En casa
            {% elif is_state("device_tracker.geni", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.geni.state }}
            {%- endif %}
      ana:
        friendly_name: 'Ana'
        value_template: >-
            {%- if is_state("device_tracker.ana", "home") %}
                En casa
            {% elif is_state("device_tracker.ana", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.ana.state }}
            {%- endif %}
      maria_del_mar:
        friendly_name: 'Maria del Mar'
        value_template: >-
            {%- if is_state("device_tracker.maria_del_mar", "home") %}
                En casa
            {% elif is_state("device_tracker.maria_del_mar", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.maria_del_mar.state }}
            {%- endif %}
      esther:
        friendly_name: 'Esther'
        value_template: >-
            {%- if is_state("device_tracker.esther", "home") %}
                En casa
            {% elif is_state("device_tracker.esther", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.esther.state }}
            {%- endif %}
      carlota:
        friendly_name: 'Carlota'
        value_template: >-
            {%- if is_state("device_tracker.carlota", "home") %}
                En casa
            {% elif is_state("device_tracker.carlota", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.carlota.state }}
            {%- endif %}
      primo_carlos:
        friendly_name: 'Primo Carlos'
        value_template: >-
            {%- if is_state("device_tracker.primo_carlos", "home") %}
                En casa
            {% elif is_state("device_tracker.primo_carlos", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.primo_carlos.state }}
            {%- endif %}
      al:
        friendly_name: 'Al'
        value_template: >-
            {%- if is_state("device_tracker.al", "home") %}
                En casa
            {% elif is_state("device_tracker.al", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.al.state }}
            {%- endif %}
      nena:
        friendly_name: 'Nena'
        value_template: >-
            {%- if is_state("device_tracker.nena", "home") %}
                En casa
            {% elif is_state("device_tracker.nena", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.nena.state }}
            {%- endif %}
      pedro:
        friendly_name: 'Pedro'
        value_template: >-
            {%- if is_state("device_tracker.pedro", "home") %}
                En casa
            {% elif is_state("device_tracker.pedro", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.pedro.state }}
            {%- endif %}
      laura_olivas:
        friendly_name: 'Laura Olivas'
        value_template: >-
            {%- if is_state("device_tracker.laura_olivas", "home") %}
                En casa
            {% elif is_state("device_tracker.laura_olivas", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.laura_olivas.state }}
            {%- endif %}
      javier:
        friendly_name: 'Javier'
        value_template: >-
            {%- if is_state("device_tracker.javier", "home") %}
                En casa
            {% elif is_state("device_tracker.javier", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.javier.state }}
            {%- endif %}
      nando:
        friendly_name: 'Nando'
        value_template: >-
            {%- if is_state("device_tracker.nando", "home") %}
                En casa
            {% elif is_state("device_tracker.nando", "not_home") %}
                Ausente
            {% else %}
                {{ states.device_tracker.nando.state }}
            {%- endif %}
      hp_photosmart_5520:
        friendly_name: 'HP Photosmart 5520'
        value_template: >-
            {%- if is_state("device_tracker.hp_photosmart_5520", "home") %}
                Encendida
            {% else %}
                Apagada
            {%- endif %}
      qnap_ts_110:
        friendly_name: 'QNAP TS-110'
        value_template: >-
            {%- if is_state("device_tracker.qnap", "home") %}
                Encendido
            {% else %}
                Apagado
            {%- endif %}

# Google travel time to work
- platform: google_travel_time
  name: 'a la oficina'
  api_key: !secret google_distance_api_key
  origin: device_tracker.hokusphone_hokusphone
  destination: zone.oficina
  options:
    language: es
    departure_time: now
    traffic_model: pessimistic

# Google travel time to home
- platform: google_travel_time
  name: 'a casa'
  api_key: !secret google_distance_api_key
  origin: device_tracker.hokusphone_hokusphone
  destination: zone.home
  options:
    language: es
    departure_time: now
    traffic_model: pessimistic

# Google travel time to school
- platform: google_travel_time
  name: 'al colegio'
  api_key: !secret google_distance_api_key
  origin: device_tracker.hokusphone_hokusphone
  destination: zone.colegio
  options:
    language: es
    departure_time: now
    traffic_model: pessimistic

#- platform: cups
#  printers:
#    - HP_Photosmart_5520

# Magenta ink level
- platform: mqtt
  state_topic: 'home/printer/magenta'
  name: ink_level_magenta
  unit_of_measurement: '%'

# Cyan ink level
- platform: mqtt
  state_topic: 'home/printer/cyan'
  name: ink_level_cyan
  unit_of_measurement: '%'

# Yellow ink level
- platform: mqtt
  state_topic: 'home/printer/yellow'
  name: ink_level_yellow
  unit_of_measurement: '%'

# black ink level
- platform: mqtt
  state_topic: 'home/printer/black'
  name: ink_level_black
  unit_of_measurement: '%'

# Temperature CPU
- platform: snmp
  name: qnap_cpu_temp
  host: 192.168.1.2
  baseoid: 1.3.6.1.4.1.24681.1.2.6.0

# Temperature HD1
- platform: snmp
  name: qnap_hd1_temp
  host: 192.168.1.2
  baseoid: 1.3.6.1.4.1.24681.1.2.11.1.3.1

# Free HD size
- platform: snmp
  name: qnap_free_hd_size
  host: 192.168.1.2
  baseoid: 1.3.6.1.4.1.24681.1.2.17.1.5.1

# Volume status
- platform: snmp
  name: qnap_vol_status
  host: 192.168.1.2
  baseoid: 1.3.6.1.4.1.24681.1.2.17.1.6.1

# HD1 Status
- platform: snmp
  name: qnap_hd1_status
  host: 192.168.1.2
  baseoid: 1.3.6.1.4.1.24681.1.2.11.1.7.1

# Total RAM
#- platform: snmp
#  name: qnap_total_ram
#  host: 192.168.1.2
#  baseoid: 1.3.6.1.4.1.24681.1.2.2.0

# Free RAM
- platform: snmp
  name: qnap_free_ram
  host: 192.168.1.2
  baseoid: 1.3.6.1.4.1.24681.1.2.3.0

# CPU Load
- platform: snmp
  name: qnap_cpu_load
  host: 192.168.1.2
  baseoid: 1.3.6.1.4.1.24681.1.2.1.0

# Uptime
#- platform: snmp
#  name: qnap_uptime
#  host: 192.168.1.2
#  baseoid: .1.3.6.1.2.1.25.1.1.0

# Model
#- platform: snmp
#  name: qnap_model
#  host: 192.168.1.2
#  baseoid: .1.3.6.1.4.1.24681.1.2.12.0